module.exports = [
  `ALTER TABLE pets ADD COLUMN level      INTEGER NOT NULL DEFAULT 1`,
  `ALTER TABLE pets ADD COLUMN exp        INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE pets ADD COLUMN skill_points INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE pets ADD COLUMN affinity   REAL    NOT NULL DEFAULT 50`,
  `ALTER TABLE pets ADD COLUMN hp         INTEGER NOT NULL DEFAULT 100`,
  `ALTER TABLE pets ADD COLUMN mp         INTEGER NOT NULL DEFAULT 100`,
  `ALTER TABLE pets ADD COLUMN attack     INTEGER NOT NULL DEFAULT 10`,
  `ALTER TABLE pets ADD COLUMN defense    INTEGER NOT NULL DEFAULT 5`,
  `ALTER TABLE pets ADD COLUMN speed      INTEGER NOT NULL DEFAULT 10`,
]
